// <auto-generated />
namespace WpfApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Maj_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Maj_02));
        
        string IMigrationMetadata.Id
        {
            get { return "201904181644164_Maj_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
