//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiningMgr.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMiningEntities : DbContext
    {
        public DbMiningEntities()
            : base("name=DbMiningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<Common> Commons { get; set; }
        public virtual DbSet<Enhancer_Info> Enhancer_Infos { get; set; }
        public virtual DbSet<Excavator_Info> Excavator_Infos { get; set; }
        public virtual DbSet<Finder_Info> Finder_Infos { get; set; }
        public virtual DbSet<FinderAmplifier_Info> FinderAmplifier_Infos { get; set; }
        public virtual DbSet<InWorld> InWorlds { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Planet> Planets { get; set; }
        public virtual DbSet<Refiner_Info> Refiner_Infos { get; set; }
        public virtual DbSet<Tool> Tools { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Unstackable> Unstackables { get; set; }
    }
}
