//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiningMgr.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finder_Info
    {
        public int Id { get; set; }
        public decimal Depth { get; set; }
        public decimal FinderRange { get; set; }
        public short BasePecSearch { get; set; }
    
        public virtual Tool Tool { get; set; }
    }
}
