//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiningMgr.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinderAmplifier_Info
    {
        public int Id { get; set; }
        public decimal Coeff { get; set; }
    
        public virtual Unstackable Unstackable { get; set; }
        public virtual Setup Setup { get; set; }
    }
}
