//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiningMgr.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup
    {
        public int Id { get; set; }
        public int SearchModeId { get; set; }
        public int FinderId { get; set; }
        public int FinderAmplifierId { get; set; }
        public Nullable<byte> FinderDepthEnhancerQty { get; set; }
        public Nullable<byte> FinderRangeEnhancerQty { get; set; }
        public Nullable<byte> FinderSkillEnhancerQty { get; set; }
    
        public virtual Common Common { get; set; }
        public virtual Finder_Info Finder_Info { get; set; }
        public virtual FinderAmplifier_Info FinderAmplifier_Info { get; set; }
        public virtual SearchMode SearchMode { get; set; }
    }
}
