//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class InWorld
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InWorld()
        {
            this.Tool = new HashSet<Tool>();
        }
    
        public int Id { get; set; }
        public int TypeId { get; set; }
        public bool IsStackable { get; set; }
        public decimal Value { get; set; }
    
        public virtual Common Common { get; set; }
        public virtual Enhancer_Info Enhancer_Info { get; set; }
        public virtual Type Type { get; set; }
        public virtual Material Material { get; set; }
        public virtual Unstackable Unstackable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tool> Tool { get; set; }
    }
}
