//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refiner_Info
    {
        public int Id { get; set; }
        public decimal Eff { get; set; }
    
        public virtual Tool Tool { get; set; }
    }
}
