//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tool()
        {
            this.InWorld = new HashSet<InWorld>();
        }
    
        public int Id { get; set; }
        public Nullable<byte> UsePerMin { get; set; }
    
        public virtual Excavator_Info Excavator_Info { get; set; }
        public virtual Finder_Info Finder_Info { get; set; }
        public virtual Refiner_Info Refiner_Info { get; set; }
        public virtual Unstackable Unstackable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InWorld> InWorld { get; set; }
    }
}
